# Generated by Django 4.1.7 on 2023-03-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="img",
            field=models.ImageField(default="cat.jpg", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(default="my image", max_length=30),
        ),
    ]
